USE [master]
GO
/****** Object:  Database [REDARBOR_TT]    Script Date: 21/09/2025 11:24:57 ******/
CREATE DATABASE [REDARBOR_TT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'REDARBOR_TT', FILENAME = N'/var/opt/mssql/data/REDARBOR_TT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'REDARBOR_TT_log', FILENAME = N'/var/opt/mssql/data/REDARBOR_TT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [REDARBOR_TT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [REDARBOR_TT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [REDARBOR_TT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET ARITHABORT OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [REDARBOR_TT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [REDARBOR_TT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [REDARBOR_TT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [REDARBOR_TT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET RECOVERY FULL 
GO
ALTER DATABASE [REDARBOR_TT] SET  MULTI_USER 
GO
ALTER DATABASE [REDARBOR_TT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [REDARBOR_TT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [REDARBOR_TT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [REDARBOR_TT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [REDARBOR_TT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [REDARBOR_TT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'REDARBOR_TT', N'ON'
GO
ALTER DATABASE [REDARBOR_TT] SET QUERY_STORE = ON
GO
ALTER DATABASE [REDARBOR_TT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [REDARBOR_TT]
GO
/****** Object:  Table [dbo].[T_EMPLOYEES]    Script Date: 21/09/2025 11:24:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_EMPLOYEES](
	[EMP_IdEmployee] [uniqueidentifier] NOT NULL,
	[EMP_Username] [nvarchar](255) NOT NULL,
	[EMP_Name] [nvarchar](255) NULL,
	[EMP_Email] [nvarchar](255) NOT NULL,
	[EMP_Fax] [nvarchar](50) NULL,
	[EMP_Password] [nvarchar](255) NOT NULL,
	[EMP_CompanyId] [int] NOT NULL,
	[EMP_PortalId] [int] NOT NULL,
	[EMP_RoleId] [int] NOT NULL,
	[EMP_StatusId] [int] NOT NULL,
	[EMP_Telephone] [nvarchar](50) NULL,
	[EMP_LastLogin] [datetime2](7) NULL,
	[EMP_CreatedOn] [datetime2](7) NOT NULL,
	[EMP_UpdatedOn] [datetime2](7) NOT NULL,
	[EMP_DeletedOn] [datetime2](7) NULL,
 CONSTRAINT [PK_T_EMPLOYEES] PRIMARY KEY CLUSTERED 
(
	[EMP_IdEmployee] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_EMPLOYEES] ADD  CONSTRAINT [DF_T_EMPLOYEES_EMP_CreatedOn]  DEFAULT (getdate()) FOR [EMP_CreatedOn]
GO
ALTER TABLE [dbo].[T_EMPLOYEES] ADD  CONSTRAINT [DF_T_EMPLOYEES_EMP_UpdatedOn]  DEFAULT (getdate()) FOR [EMP_UpdatedOn]
GO
USE [master]
GO
ALTER DATABASE [REDARBOR_TT] SET  READ_WRITE 
GO
