USE [CAMPING_AI_DB]
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'T_CAMPINGS_IMPORT')
BEGIN
	CREATE TABLE [dbo].[T_CAMPINGS_IMPORT] (
		[CMI_IdCamping]  UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_T_CAMPINGS_IMPORT_Id]        DEFAULT NEWID(),
		[CMI_ExternalId] NVARCHAR(100)    NOT NULL,
		[CMI_Source]     NVARCHAR(50)     NOT NULL CONSTRAINT [DF_T_CAMPINGS_IMPORT_Source]    DEFAULT N'OpenStreetMap',
		[CMI_Name]       NVARCHAR(500)    NOT NULL,
		[CMI_Latitude]   DECIMAL(10, 7)   NULL,
		[CMI_Longitude]  DECIMAL(10, 7)   NULL,
		[CMI_Address]    NVARCHAR(500)    NULL,
		[CMI_PostalCode] NVARCHAR(20)     NULL,
		[CMI_City]       NVARCHAR(200)    NULL,
		[CMI_Province]   NVARCHAR(200)    NULL,
		[CMI_Country]    NVARCHAR(100)    NULL,
		[CMI_Phone]      NVARCHAR(50)     NULL,
		[CMI_Email]      NVARCHAR(200)    NULL,
		[CMI_Website]    NVARCHAR(500)    NULL,
		[CMI_CreatedOn]  DATETIME2        NOT NULL CONSTRAINT [DF_T_CAMPINGS_IMPORT_CreatedOn] DEFAULT GETDATE(),
		[CMI_UpdatedOn]  DATETIME2        NOT NULL CONSTRAINT [DF_T_CAMPINGS_IMPORT_UpdatedOn] DEFAULT GETDATE(),
		CONSTRAINT [PK_T_CAMPINGS_IMPORT]           PRIMARY KEY CLUSTERED ([CMI_IdCamping]),
		CONSTRAINT [UQ_T_CAMPINGS_IMPORT_ExternalId] UNIQUE ([CMI_ExternalId])
	);

	PRINT 'Tabla T_CAMPINGS_IMPORT creada correctamente.';
END
ELSE
BEGIN
	PRINT 'La tabla T_CAMPINGS_IMPORT ya existe. No se realizaron cambios.';
END
GO

-- Consultas de validación
-- SELECT COUNT(*)  FROM T_CAMPINGS_IMPORT
-- SELECT *         FROM T_CAMPINGS_IMPORT WHERE CMI_Latitude IS NULL OR CMI_Longitude IS NULL
-- SELECT CMI_ExternalId, COUNT(*) FROM T_CAMPINGS_IMPORT GROUP BY CMI_ExternalId HAVING COUNT(*) > 1
